
import Script from 'next/script'

export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      {/* <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tw-elements/dist/css/index.min.css" /> */}
      {/* <Script  src="https://cdn.jsdelivr.net/npm/tw-elements/dist/css/index.min.css" strategy="lazyOnload" /> */}
    </>
  )
}
